# Generated by Django 2.1.4 on 2018-12-12 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recette', '0002_ingredient_recette'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='recette',
            new_name='recettes',
        ),
    ]
