# Generated by Django 2.1.4 on 2018-12-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recette', '0003_auto_20181212_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='recettes',
        ),
        migrations.AddField(
            model_name='recette',
            name='ingredients',
            field=models.ManyToManyField(through='recette.IngredientRecette', to='recette.Ingredient'),
        ),
    ]
