# Generated by Django 2.1.4 on 2018-12-14 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recette', '0005_ingredientrecette_quantite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='unite',
        ),
        migrations.AddField(
            model_name='ingredientrecette',
            name='unite',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
